GET http://localhost:3000/products

###

GET http://localhost:3000/products/category

###

GET http://localhost:3000/products/category/Trains
Content-Type: application/json


###

GET http://localhost:3000/offices


###

GET http://localhost:3000/users